name: Publish docker images

on:
  push:
    tags:
      - v*.*.*

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Extract version
        run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Build and push eps
        uses: docker/build-push-action@v1
        with:
          build_args: |
            VERSION=$VERSION
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PW }}        
          repository: inoeg/eps
          tag_with_ref: true
          dockerfile: ./docker/Eps.dockerfile
      - name: Build and push sd
        uses: docker/build-push-action@v1
        with:
          build_args: |
            VERSION=$VERSION
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PW }}        
          repository: inoeg/sd
          tag_with_ref: true
          dockerfile: ./docker/Sd.dockerfile
      - name: Build and push proxy
        uses: docker/build-push-action@v1
        with:
          build_args: |
            VERSION=$VERSION
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PW }}        
          repository: inoeg/proxy
          tag_with_ref: true
          dockerfile: ./docker/Proxy.dockerfile
