name: Publish docker images

on:
  push:
    tags:
      - v*.*.*

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Extract version
        run: echo VERSION=${GITHUB_REF#refs/*/} >> $GITHUB_ENV
      - name: Check output
        env:
          VERSION: ${{ env.VERSION }}
        run: |
          echo $VERSION
          echo ${{ env.VERSION }}
      - name: Create image tag
        id: meta_eps
        uses: docker/metadata-action@v3
        with:
          images: inoeg/eps
      - name: Build and push eps
        uses: docker/build-push-action@v2.9.0
        with:
          build-args: VERSION=${{ env.VERSION }}
          context: ./docker/
          file: {context}/Eps.dockerfile
          tags: ${{ steps.meta_eps.outputs.tags }}
          push: false
          load: true
          labels: |
            iris.client-eps.image.revision=${{ github.sha }}
      - name: Sign and push docker image
        uses: sudo-bot/action-docker-sign@latest
        with:
          image-ref: 'inoeg/eps:${{ env.VERSION }}'
          private-key-id: ${{ secrets.DOCKER_HUB_DCT_PRIVATE_KEY_IDENTIFIER }}
          private-key: ${{ secrets.DOCKER_HUB_DCT_PRIVATE_KEY }}
          private-key-passphrase: ${{ secrets.DOCKER_HUB_DCT_PASSPHRASE }}
      - name: Build and push sd
        uses: docker/build-push-action@v1
        with:
          build_args: VERSION=${{ env.VERSION }}
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PW }}        
          repository: inoeg/sd
          tag_with_ref: true
          dockerfile: ./docker/Sd.dockerfile
      - name: Build and push proxy
        uses: docker/build-push-action@v1
        with:
          build_args: VERSION=${{ env.VERSION }}
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PW }}        
          repository: inoeg/proxy
          tag_with_ref: true
          dockerfile: ./docker/Proxy.dockerfile
