name: Publish docker images

on:
  push:
    tags:
      - v*.*.*

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Extract version
        run: echo VERSION=${GITHUB_REF#refs/*/} >> $GITHUB_ENV
      - name: Check output
        env:
          VERSION: ${{ env.VERSION }}
        run: |
          echo $VERSION
          echo ${{ env.VERSION }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PW }}

      - name: Create eps image tag
        id: meta_eps
        uses: docker/metadata-action@v3
        with:
          images: inoeg/eps
      - name: Build eps
        uses: docker/build-push-action@v2.9.0
        with:
          build-args: VERSION=${{ env.VERSION }}
          file: ./docker/Eps.dockerfile
          tags: ${{ steps.meta_eps.outputs.tags }}
          push: false
          load: true
          labels: |
            iris.eps.image.revision=${{ github.sha }}
      - name: Sign and push versioned eps image
        uses: sudo-bot/action-docker-sign@latest
        with:
          image-ref: ${{steps.meta_eps.outputs.tags[0]}}
          private-key-id: ${{ secrets.DOCKER_HUB_DCT_PRIVATE_KEY_IDENTIFIER }}
          private-key: ${{ secrets.DOCKER_HUB_DCT_PRIVATE_KEY }}
          private-key-passphrase: ${{ secrets.DOCKER_HUB_DCT_PASSPHRASE }}
      - name: Sign and push latest eps image
        uses: sudo-bot/action-docker-sign@latest
        with:
          image-ref: ${{steps.meta_eps.outputs.tags[1]}}
          private-key-id: ${{ secrets.DOCKER_HUB_DCT_PRIVATE_KEY_IDENTIFIER }}
          private-key: ${{ secrets.DOCKER_HUB_DCT_PRIVATE_KEY }}
          private-key-passphrase: ${{ secrets.DOCKER_HUB_DCT_PASSPHRASE }}

      - name: Create sd image tag
        id: meta_sd
        uses: docker/metadata-action@v3
        with:
          images: inoeg/sd
      - name: Build sd
        uses: docker/build-push-action@v2.9.0
        with:
          build-args: VERSION=${{ env.VERSION }}
          file: ./docker/Sd.dockerfile
          tags: ${{ steps.meta_sd.outputs.tags }}
          push: false
          load: true
          labels: |
            iris.sd.image.revision=${{ github.sha }}
      - name: Sign and push sd image
        uses: sudo-bot/action-docker-sign@latest
        with:
          image-ref: ${{steps.meta_sd.outputs.tags}}
          private-key-id: ${{ secrets.DOCKER_HUB_DCT_PRIVATE_KEY_IDENTIFIER }}
          private-key: ${{ secrets.DOCKER_HUB_DCT_PRIVATE_KEY }}
          private-key-passphrase: ${{ secrets.DOCKER_HUB_DCT_PASSPHRASE }}

      - name: Create proxy image tag
        id: meta_proxy
        uses: docker/metadata-action@v3
        with:
          images: inoeg/proxy
      - name: Build proxy
        uses: docker/build-push-action@v2.9.0
        with:
          build-args: VERSION=${{ env.VERSION }}
          file: ./docker/Proxy.dockerfile
          tags: ${{ steps.meta_proxy.outputs.tags }}
          push: false
          load: true
          labels: |
            iris.proxy.image.revision=${{ github.sha }}
      - name: Sign and push proxy image
        uses: sudo-bot/action-docker-sign@latest
        with:
          image-ref: ${{steps.meta_proxy.outputs.tags}}
          private-key-id: ${{ secrets.DOCKER_HUB_DCT_PRIVATE_KEY_IDENTIFIER }}
          private-key: ${{ secrets.DOCKER_HUB_DCT_PRIVATE_KEY }}
          private-key-passphrase: ${{ secrets.DOCKER_HUB_DCT_PASSPHRASE }}