name: Publish docker images

on:
  push:
#    tags:
#      - v*.*.*
    branches: [feature/docker-image]

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to docker.io
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PW }}
          repository: inoeg/eps
          tag_with_ref: true
          path: ./docker/Eps.dockerfile
