name: Publish docker images

on:
  push:
    tags:
      - v*.*.*

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - run: echo ${{ steps.get_version.outputs.major }}
      - run: echo ${{ steps.get_version.outputs.minor }}
      - name: Build and push eps
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PW }}        
          repository: inoeg/eps
          tags: ${{ steps.get_version.outputs.VERSION }}
          dockerfile: ./docker/Eps.dockerfile
      - name: Build and push sd
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PW }}        
          repository: inoeg/sd
          tag_with_ref: true
          dockerfile: ./docker/Sd.dockerfile
      - name: Build and push proxy
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PW }}        
          repository: inoeg/proxy
          tag_with_ref: true
          dockerfile: ./docker/Proxy.dockerfile
