name: Build the documentation website

on:
  push:
    branches:
      - main
      - feature/docs # just for testing

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up docs
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          sudo apt-get update -qy
          sudo apt-get install -y curl tidy optipng python3 python3-pip locales rsync nodejs npm openssh-client expect
          sudo pip3 install virtualenv
          sudo npm install -g n
          sudo n 15
          sudo sh -c 'echo "en_US UTF-8" > /etc/locale.gen'
          sudo locale-gen en_US.UTF-8
          export LANG=en_US.UTF-8
          export LANGUAGE=en_US:en
          export LC_ALL=en_US.UTF-8
          make setup
      - name: Build docs
        run: |
          make SITE=src/site-prod.yml
          make optimize-html
      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: docs/build